services:
  - type: web
    name: alarm-system
    env: node
    buildCommand: npm install && npm run build:client
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false  # You'll need to set this through the Render dashboard
      # Add any other environment variables your application needs
    autoDeploy: true 